apiVersion: v1
kind: Service
metadata:
  name: hello-service-lb
  namespace: default
  labels:
    app: myhello
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:    
    app: myhello
  type: LoadBalancer
